"""
1id.com Enrollment API -- Pydantic request/response models

Matches the API specification in 030_technical_architecture.md Section 3.2.
All responses use the standard envelope: { ok, data, error }.
"""

from pydantic import BaseModel, Field
from typing import Optional, List


# =====================================================================
# Standard response envelope
# =====================================================================

class APIError(BaseModel):
  code: str
  message: str


class APIEnvelope(BaseModel):
  """Every response uses this envelope."""
  ok: bool
  data: Optional[dict] = None
  error: Optional[APIError] = None


# =====================================================================
# POST /api/v1/enroll/declared
# =====================================================================

class DeclaredEnrollmentRequest(BaseModel):
  """Request body for declared-tier enrollment (no TPM required)."""
  software_key_pem: str = Field(
    ...,
    description="PEM-encoded public key generated by the SDK (Ed25519, ECDSA, or RSA)"
  )
  operator_email: Optional[str] = Field(
    None,
    description="Optional human operator email (for communication, not identity)"
  )
  requested_handle: Optional[str] = Field(
    None,
    description="Desired vanity handle without @ prefix (e.g. 'my-cloud-agent')"
  )


# =====================================================================
# POST /api/v1/enroll/begin  (sovereign/virtual tier -- TPM)
# =====================================================================

class SovereignEnrollmentBeginRequest(BaseModel):
  """Request body to begin TPM-based enrollment."""
  ek_certificate_pem: str = Field(
    ...,
    description="PEM-encoded X.509 EK certificate from TPM"
  )
  ek_certificate_chain_pem: Optional[List[str]] = Field(
    None,
    description="PEM-encoded intermediate CA certs the client found locally (best-effort)"
  )
  ak_public_key_pem: str = Field(
    ...,
    description="PEM-encoded public portion of the Attestation Identity Key"
  )
  operator_email: Optional[str] = None
  requested_handle: Optional[str] = None


# =====================================================================
# POST /api/v1/enroll/activate  (complete sovereign enrollment)
# =====================================================================

class EnrollmentActivateRequest(BaseModel):
  """Request body to complete enrollment via credential activation."""
  enrollment_session_id: str = Field(
    ...,
    description="Session ID from the /enroll/begin response"
  )
  decrypted_credential: str = Field(
    ...,
    description="Base64-encoded decrypted challenge proving TPM possession"
  )


# =====================================================================
# POST /api/v1/verify/challenge  (live verification by relying party)
# =====================================================================

class VerifyChallengeRequest(BaseModel):
  agent_id: str
  nonce: str = Field(..., description="Random 64-byte hex string")
  callback_url: Optional[str] = None


# =====================================================================
# Handle management
# =====================================================================

class HandleRegisterRequest(BaseModel):
  handle_name: str = Field(..., description="Desired handle without @ prefix")


class HandleRenewRequest(BaseModel):
  handle_name: str


# =====================================================================
# Response data models (used inside APIEnvelope.data)
# =====================================================================

class IdentityData(BaseModel):
  internal_id: str
  handle: str
  trust_tier: str
  tpm_manufacturer: Optional[str] = None
  registered_at: str


class CredentialsData(BaseModel):
  client_id: str
  client_secret: str
  token_endpoint: str
  grant_type: str = "client_credentials"


class TokensData(BaseModel):
  access_token: str
  refresh_token: Optional[str] = None
  expires_in: int
  token_type: str = "Bearer"


class EnrollmentCompleteData(BaseModel):
  """Data returned after successful enrollment (declared or activate)."""
  identity: IdentityData
  credentials: CredentialsData
  initial_tokens: Optional[TokensData] = None
